use parse_display::Display;

#[derive(Debug, Display)]
pub enum Lottery {
    #[display("thailotto")]
    Thai,
    #[display("laoslotto")]
    Lao,
    #[display("hanoylotto")]
    Hanoi,
    #[display("hanoylottovip")]
    HanoiVip,
    #[display("baaclotto")]
    Baac,
    #[display("gsblotto")]
    Gsb,
    #[display("pingponglotto")]
    PingPong,
    #[display("laoslotto_set")]
    LaoSet,
    #[display("yeekeelotto")]
    Yeekee,
    #[display("malaylotto")]
    Malaysian,
    #[display("hanoylotto_set")]
    HanoiSet,
    #[display("hanoylottovip_set")]
    HanoiVipSet,
    #[display("hanoylottospecial_set")]
    HanoiSpecialSet,
    #[display("malaylotto_set")]
    MalaySet,
    #[display("hanoylottospecial")]
    HanoiSpecial,
    #[display("stockkorea")]
    StockKorea,
    #[display("stockchina")]
    StockChina,
    #[display("stockdowjones")]
    StockDowJones,
    #[display("stockdowjonesvip")]
    StockDowJonesVip,
    #[display("stocktaiwan")]
    StockTaiwan,
    #[display("stockengland")]
    StockBritish,
    #[display("stockindia")]
    StockIndia,
    #[display("stockhangseng")]
    StockHangSeng,
    #[display("stockegypt")]
    StockEgyptian,
    #[display("stocknikkei")]
    StockNikkei,
    #[display("stocksingapore")]
    StockSingapore,
    #[display("stockthai")]
    StockThai,
    #[display("stockgerman")]
    StockGerman,
    #[display("stockrussia")]
    StockRussian,
    #[display("stock")]
    StockCollect,
    #[display("zodiaclotto")]
    Zodiac,
    #[display("pingponglotto2")]
    PingPong2,
    #[display("pingponglotto3")]
    PingPong3,
    #[display("pingponglotto6")]
    PingPong6,
    #[display("hanoylottostar_set")]
    HanoiStarSet,
    #[display("hanoylottostar")]
    HanoiStar,
    #[display("hanoylottotv")]
    HanoiTv,
    #[display("hanoylottotv_set")]
    HanoiTvSet,
    #[display("laoslottoextra")]
    LaoExtra,
    #[display("laoslottoextra_set")]
    LaoExtraSet,
    #[display("laoslottohd")]
    LaoHd,
    #[display("laoslottohd_set")]
    LaoHdSet,
    #[display("laoslottotv")]
    LaoTv,
    #[display("laoslottotv_set")]
    LaoTvSet,
}
