use parse_display::Display;

#[derive(Debug, Display)]
pub enum OnlineCasinoProvider {
    #[display("evoplay_online_casino")]
    Evoplay,
    #[display("bet_games_online_casino")]
    BetGames,
    #[display("pg_online_casino")]
    PG,
    #[display("ambpoker_online_casino")]
    AmbPoker,
    #[display("slot_xo_online_casino")]
    SlotXO,
    #[display("dragoon_online_casino")]
    Dragoon,
    #[display("jili_online_casino")]
    Jili,
    #[display("mg_online_casino")]
    MG,
    #[display("gaming_soft_online_casino")]
    GamingSoft,
    #[display("ambslot_online_casino")]
    AmbSlot,
    #[display("habanero_online_casino")]
    Habanero,
    #[display("astro_tech_online_casino")]
    AstroTech,
    #[display("iconic_gaming_online_casino")]
    IconicGaming,
    #[display("funta_online_casino")]
    FunTa,
    #[display("all_way_spin_online_casino")]
    AllWaySpin,
    #[display("ka_gaming_online_casino")]
    KaGaming,
    #[display("kingmaker")]
    Kingmaker,
    #[display("netent_online_casino")]
    Netent,
    #[display("red_tiger_online_casino")]
    RedTiger,
    #[display("arcadia")]
    Arcadia,
    #[display("ninja_online_casino")]
    Ninja,
    #[display("kiss_online_casino")]
    Kiss,
}
