use parse_display::Display;

#[derive(Debug, Display)]
pub enum SlotProvider {
    #[display("slot_xo_slot")]
    SlotXO,
    #[display("pg_slot")]
    PG,
    #[display("evoplay_slot")]
    Evoplay,
    #[display("simpleplay")]
    SimplePlay,
    #[display("spade")]
    Spade,
    #[display("ambpoker_slot")]
    AmbPoker,
    #[display("ambslot_slot")]
    AmbSlot,
    #[display("pragmatic_slot")]
    Pragmatic,
    #[display("dragoon_slot")]
    Dragoon,
    #[display("jili_slot")]
    Jili,
    #[display("mannaplay")]
    MannaPlay,
    #[display("royal_slot_gaming")]
    RoyalSlotGaming,
    #[display("mg_slot")]
    MG,
    #[display("upg_slot")]
    UPG,
    #[display("gaming_soft_slot")]
    GamingSoft,
    #[display("ygg_slot")]
    YGG,
    #[display("slotmill")]
    Slotmill,
    #[display("habanero_slot")]
    Habanero,
    #[display("astro_tech_slot")]
    AstroTech,
    #[display("wazdan")]
    Wazdan,
    #[display("all_way_spin_slot")]
    AllWaySpin,
    #[display("booongo")]
    Booongo,
    #[display("funta_slot")]
    FunTa,
    #[display("iconic_gaming_slot")]
    IconicGaming,
    #[display("gamatron")]
    Gamatron,
    #[display("ka_gaming_slot")]
    KaGaming,
    #[display("play_son")]
    PlaySon,
    #[display("wm_slot")]
    WM,
    #[display("ameba")]
    Ameba,
    #[display("i8")]
    I8,
    #[display("creative_gaming")]
    CreativeGaming,
    #[display("red_tiger_slot")]
    RedTiger,
    #[display("netent_slot")]
    Netent,
    #[display("relax")]
    Relax,
    #[display("ninja_slot")]
    Ninja,
    #[display("kiss_slot")]
    Kiss,
    #[display("spinix_slot")]
    Spinix,
    #[display("dragon_gaming")]
    DragonGaming,
    #[display("hacksaw")]
    Hacksaw,
}
